### PR TITLE
fix: liquidation prices

### LINKED ISSUE #402: Invalid liquidation prices
## Description

- Confirm if liquidation prices is valid
  - Profit loss(Take profit) price
  - Loss cut(Stop loss) price

- Compare with the provided spec

### PR DESCRIPTION
**Pull request by austin-builds**
## Description

- Liquidation price with latest spec
  - Profit stop(Take profit) price
  - Loss cut(Stop loss) price

- Leverage and Stop Loss in contract quantity input

## Related Issues

- Fixes #402

### CODE REVIEW

**Comment by not-thing** [comment]
related to https://github.com/chromatic-protocol/frontend/issues/404

**Review by not-thing — APPROVED** [review]
@austin-builds, @jaycho-46 
will you fix the maximum value of profitstop when open a `short` position? 
at #397

**Comment by jaycho-46** [comment]
I had mentioned that I would handle this issue, but it seems like it wasn't properly communicated. I apologize for the confusion.

In the current logic, there is an issue with the calculation of 'takerMargin' and 'makerMargin' when 'qty' is selected.
And there was an rendering issue of 'takeProfit' and 'stopLoss' ratios, they both resolved in #397.

**Comment by jaycho-46** [comment]
@not-thing and yes. That issue will also be resolved in #397."

**Pull request closed without merging**
